use_frameworks!

target 'WRCalendarView_Example' do
  pod 'WRCalendarView', :path => '../'
  pod 'DropDownMenuKit'
  
  target 'WRCalendarView_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
